openapi: 3.0.1
info:
  description: Parent pom providing dependency and plugin management for applications
    built with Maven
  license:
    name: Apache 2.0
    url: http://springdoc.org
  termsOfService: http://swagger.io/terms/
  title: sample application API
  version: "1"
servers:
- description: Generated server url
  url: http://localhost:8080
paths:
  /person/{id}:
    get:
      operationId: one
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Person'
          description: Invalid URL or the person does not exist
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Person'
          description: Person Found
      tags:
      - person-controller
      x-accepts: '*/*'
  /person:
    post:
      operationId: person
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
      responses:
        "404":
          content:
            '*/*':
              schema:
                type: string
          description: default response
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Person'
          description: default response
      tags:
      - person-controller
      x-contentType: application/json
      x-accepts: '*/*'
components:
  schemas:
    Person:
      example:
        firstName: firstName
        lastName: lastName
        creditCardNumber: creditCardNumber
        id: 0
        email: email
        age: 79
      properties:
        id:
          format: int64
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        age:
          format: int32
          maximum: 120
          minimum: 18
          type: integer
        creditCardNumber:
          type: string
      required:
      - lastName
      type: object
      xml:
        name: person

